---
title: "Report"
author: '20063373'
date: "7/9/2021"
output:
pdf_document :
      latex_engine : xelatex
mainfont : NanumGothic
---

```{r}
library(dplyr)
library(survey)
library(tidyverse)
library(srvyr)
library(flexsurv)
library(flexsurvcure)
library(tinytex)
setwd("~/Rstudio")

# read data
data <- read.csv("tb_data_aggregate.csv")
data <- as.data.frame(data)

# pre-entry screening countries
datanew <-
  filter(
    data,
    iso_a3_nat %in%
      c("KHM","BFA","BGD","CIV","ERI","GHA","KEN","LAO",
        "NER","PAK","SOM","SDN","TZA","THA","TGO"))
# pre-entry screening countries
tb_data <-
  filter(
    data,
    iso_a3_nat %in%
      c("KHM","BFA","BGD","CIV","ERI","GHA","KEN","LAO",
        "NER","PAK","SOM","SDN","TZA","THA","TGO")) %>%
  mutate(uk_stay_yrs = round(length_uk_stay/365.25, 1),
         yr_grp = cut(uk_stay_yrs, c(0,1, 2, 3,4,5, 10, 1000)))
data2 <-
  filter(
    tb_data,
    uk_tb%in%
      c("1"))

tb_data$iso_a3_nat <- as.factor(tb_data$iso_a3_nat)
datanew$iso_a3_nat <- as.factor(datanew$iso_a3_nat)
```
```{r}

#uk_tb
data_year<-
  group_by(data2,yr_grp) %>%
  summarise(N = sum(n))
data_year
#sex
data_sex2<-
  group_by(data2,sex) %>%
  summarise(N = sum(n))
data_sex
#age
data_age2<-
  group_by(data2,agegp) %>%
  summarise(N = sum(n))
data_age2
```


```{r}
summary(datanew)
```

## raw data plots

```{r}
#plot for length_uk_stay
data_length_uk_stay <-
  group_by(datanew, length_uk_stay) %>%
  summarise(N = sum(n))
data_length_uk_stay

plot(data_length_uk_stay, ylim = c(0, 500))

plot(data_length_uk_stay, ylim = c(0, 500), xlim = c(0, 400), type = "h")
abline(v = 365.25/12*5, col = "red")
abline(v = 365.25/12*11, col = "red")

plot(data_length_uk_stay, ylim = c(0, 700), xlim = c(400, 2200), type = "h")
abline(v = 365.25*3, col = "red")
```

```{r}
# gender
data_sex<-
  group_by(datanew, sex) %>%
  summarise(N = sum(n))
data_sex
barplot(data_sex$N, names.arg = data_sex$sex)
```

```{r}
# age
data_age<-
  group_by(datanew, agegp) %>%
  summarise(N = sum(n))
data_age
barplot(data_age$N, names.arg = data_age$agegp)
barplot(data_age$N, names.arg = data_age$agegp)
```

```{r}
# nations
data_iso_a3_nat<-
  group_by(datanew, iso_a3_nat) %>% 
  summarise(N = sum(n))
data_iso_a3_nat
barplot(data_iso_a3_nat$N, names.arg = data_iso_a3_nat$iso_a3_nat)

# log scale
barplot(data_iso_a3_nat$N, names.arg = data_iso_a3_nat$iso_a3_nat, log = "y")
```

## raw data summary statistics

```{r}
#weighted mean for gender
my_des <- datanew %>%
    as_survey_design(ids=1, #no cluster
                     weights=n)
my_des %>%   
    group_by(sex) %>%  
    summarize(proportion=survey_mean(),
              total=survey_total())
```

```{r}
#weighted mean for age
my_des2 <- datanew %>%
    as_survey_design(ids=1, #no cluster
                     weights=n)
my_des2 %>%   
    group_by(agegp) %>%  
    summarize(proportion=survey_mean(),
              total=survey_total())
```

```{r}
# frequency table using a survey object
my_des3 <-
  tb_data %>%
  as_survey_design(ids = 1, weights = n)


my_des3 %>%  
  group_by(yr_grp) %>%  
  summarize(proportion = survey_mean(),
            total = survey_total())
```

```{r}
#weighted mean for nations
my_des4 <-
  datanew %>%
  as_survey_design(ids=1, #no cluster
                   weights=n)
my_des4 %>%   
    group_by(iso_a3_nat) %>%  
    summarize(proportion=survey_mean(),
              total=survey_total())
```
```{r}
#weighted mean for uk_tb
my_des5 <-
  datanew %>%
  as_survey_design(ids=1, #no cluster
                   weights=n)
my_des5 %>%   
    group_by(uk_tb) %>%  
    summarize(proportion=survey_mean(),
              total=survey_total())
```


## mixture cure modelling

```{r,warning=FALSE}
#or length_uk_stay
# no covariates

cure_llogis1 <-
  flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ 1,
               data = tb_data ,
               weights = n,
               dist = "llogis")
cure_weibull1 <-
  flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ 1,
               data = tb_data ,
               weights = n,
               dist = "weibull")
cure_gamma1 <-
  flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ 1,
               data = tb_data ,
               weights = n,
               dist = "gamma")
cure_exp1 <-
  flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ 1,
               data = tb_data ,
               weights = n,
               dist = "exp")
cure_lnorm1 <-
  flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ 1,
               data = tb_data ,
               weights = n,
               dist = "lnorm")
```

```{r}
plot(cure_llogis1, ylim = c(0.99,1),ci = FALSE)
plot(cure_weibull1, add = TRUE, col = "blue",ci = FALSE)
plot(cure_gamma1, add = TRUE, col = "green",ci = FALSE)
plot(cure_exp1, add = TRUE, col = "purple",ci = FALSE)
plot(cure_lnorm1, add = TRUE, col = "red",ci = FALSE)
#what does this plot show,what useful information could I get from this plot
```

```{r}
#plot for length_uk_stay
# mixed
#for loggis
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pllogis(
    q = seq(0.00001, 80, 0.1),
    shape = 1.573,
    scale = 6.932,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "black",
  ylab = "S",
  xlab = "year",
)

#for weibull
lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pweibull(
    q = seq(0.00001, 80, 0.1),
    shape = 1.5748,
    scale = 5.5594,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)


#for gamma
lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pgamma(
    q = seq(0.00001, 80, 0.1),
    shape = 1.7821,
    rate = 0.1829 ,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "green",
  ylab = "S",
  xlab = "year",
)

#for exp
lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pexp(
    q = seq(0.00001, 80, 0.1),
    rate = 9.19e-04 ,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "purple",
  ylab = "S",
  xlab = "year",
)


#for lnorm
lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*plnorm(
    q = seq(0.00001, 80, 0.1),
    meanlog = 5.503 ,
    sdlog = 1.894,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "red",
  ylab = "S",
  xlab = "year",
)


```


```{r,warning=FALSE}
#for sex part
cure_llogis2 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ sex,
             data =tb_data ,
             weights = n,
             dist = "llogis")

cure_weibull2 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ sex,
             data = tb_data ,
             weights = n,
             dist = "weibull")

cure_gamma2 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ sex,
             data = tb_data,
             weights = n,
             dist = "gamma")
cure_exp2 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ sex,
             data = tb_data ,
             weights = n,
             dist = "exp")
cure_lnorm2 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ sex,
             data = tb_data ,
             weights = n,
             dist = "lnorm")
```


```{r}
par(mfrow=c(2,3))
plot(cure_llogis2, ylim = c(0.99,1),col = "black",ci=FALSE)
plot(cure_weibull2, ylim = c(0.99,1),col = "blue",ci=FALSE)
plot(cure_gamma2, ylim = c(0.99,1),col = "green",ci=FALSE)
plot(cure_exp2 , ylim = c(0.99,1),col = "purple",ci=FALSE)
plot(cure_lnorm2, ylim = c(0.99,1),col = "red",ci=FALSE)
```



```{r}
par(mfrow=c(2,3))
## uncured only
plot(
  seq(0.00001, 8, 0.1),
  pllogis(
    q = seq(0.0001, 8, 0.1),
    shape = 1.6780,
    scale = 9.5822,
    lower.tail = FALSE),
  type = "l",
  xlab = "year",
  ylab = "S",
  col="blue",
  ylim = c(0,1))

lines(
  seq(0.00001, 8, 0.1),
  pllogis(
    q = seq(0.0001, 8, 0.1),
    shape = 1.6780,
    scale = 9.5822*exp(-0.0275),
    lower.tail = FALSE),
  type = "l",
  xlab = "year",
  ylab = "S",
  col = "red")

# mixed
#for loggis
#blue for F red for M
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pllogis(
    q = seq(0.00001, 80, 0.1),
    shape = 1.678,
    scale = 9.5822,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pllogis(
    q = seq(0.00001, 80, 0.1),
    shape = 1.678,
    scale = 9.5822*exp(-0.0275), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for weibull
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pweibull(
    q = seq(0.00001, 80, 0.1),
    shape = 1.6725,
    scale = 7.0703,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pweibull(
    q = seq(0.00001, 80, 0.1),
    shape = 1.6725,
    scale = 7.0703*exp(-0.0267), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for gamma
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pgamma(
    q = seq(0.00001, 80, 0.1),
    shape = 1.7806,
    rate = 0.1814 ,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pgamma(
    q = seq(0.00001, 80, 0.1),
    shape = 1.7806,
    rate = 0.1814*exp(-0.0256), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for exp
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pexp(
    q = seq(0.00001, 80, 0.1),
    rate = 9.35e-04,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pexp(
    q = seq(0.00001, 80, 0.1),
      rate = 9.35e-04*log(1.23), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for loggis
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*plnorm(
    q = seq(0.00001, 80, 0.1),
    meanlog = 5.6058 ,
    sdlog = 1.9109,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*plnorm(
    q = seq(0.00001, 80, 0.1),
    meanlog = 5.6058*-0.0370 ,
    sdlog = 1.9109, # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
```


```{r,warning=FALSE}
#for age_group
tb_data$agegp<-as.factor(tb_data$agegp)
cure_llogis3 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ agegp,
             data = tb_data ,
             weights = n,
             dist = "llogis")

cure_weibull3 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ agegp,
             data = tb_data ,
             weights = n,
             dist = "weibull")

cure_gamma3 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ agegp,
             data = tb_data,
             weights = n,
             dist = "gamma")
cure_exp3 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ agegp,
             data = tb_data ,
             weights = n,
             dist = "exp")
cure_lnorm3 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ agegp,
             data = tb_data,
             weights = n,
             dist = "lnorm")
```


```{r}
par(mfrow=c(2,3))
plot(cure_llogis3, ylim = c(0.99,1),col = "black",ci=FALSE)
plot(cure_weibull3,ylim = c(0.99,1),col = "blue",ci=FALSE)
plot(cure_gamma3,ylim = c(0.99,1),col = "green",ci=FALSE)
plot(cure_exp3, ylim = c(0.99,1), col = "purple",ci=FALSE)
plot(cure_lnorm3, ylim = c(0.99,1), col = "red",ci=FALSE)
```


```{r}
#blue for gp1(11-20) and red for gp2(20-39)
par(mfrow=c(2,3))
# mixed

plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pllogis(
    q = seq(0.00001, 80, 0.1),
    shape = 1.6787,
    scale = 9.5310,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pllogis(
    q = seq(0.00001, 80, 0.1),
    shape = 1.6387,
    scale = 9.5310*exp(0.0975), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for weibull
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pweibull(
    q = seq(0.00001, 80, 0.1),
    shape = 1.6730,
    scale = 7.0422,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pweibull(
    q = seq(0.00001, 80, 0.1),
    shape = 1.6730,
    scale = 7.0422*exp(0.0958), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for gamma
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pgamma(
    q = seq(0.00001, 80, 0.1),
    shape = 1.7816,
    rate = 0.1819 ,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pgamma(
    q = seq(0.00001, 80, 0.1),
    shape = 1.7816,
    rate = 0.1819*exp(0.0963), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for exp
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pexp(
    q = seq(0.00001, 80, 0.1),
    rate = 9.72e-04,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*pexp(
    q = seq(0.00001, 80, 0.1),
      rate = 9.72e-04*log(1.66), # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
#for lnorm
plot(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*plnorm(
    q = seq(0.00001, 80, 0.1),
    meanlog = 5.5806 ,
    sdlog = 1.9067,
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.98, 1.00001),
  col = "blue",
  ylab = "S",
  xlab = "year",
)

lines(
  seq(0.00001, 80, 0.1),
  0.9799 + 0.0201*plnorm(
    q = seq(0.00001, 80, 0.1),
    meanlog = 5.5806*0.1311 ,
    sdlog = 1.9067, # sexM parameter
    lower.tail = FALSE),
  type = "l",
  ylim = c(0.99, 1.00001),
  col = "red")
```

### nationality

```{r,warning=FALSE}
#for different nations
cure_llogis4 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ iso_a3_nat,
             data = tb_data ,
             weights = n,
             dist = "llogis")

cure_weibull4 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ iso_a3_nat,
             data = tb_data ,
             weights = n,
             dist = "weibull")

cure_gamma4 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~iso_a3_nat,
             data = tb_data ,
             weights = n,
             dist = "gamma")
cure_gompertz4 <- flexsurvcure(Surv(uk_stay_yrs, uk_tb) ~ iso_a3_nat,
             data = tb_data ,
             weights = n,
             dist = "gompertz")
```

```{r}
plot(cure_llogis4,
     ylim = c(0.99,1),
     col = 1:15,
     col.obs = 0,
     lty = rep(c(1,2), each = 8))

legend("bottomleft",
       legend = levels(tb_data$iso_a3_nat),
       lty = rep(c(1,2), each = 8),
       col = 1:15,cex=0.4)
```

```{r}
plot(
  seq(0.00001, 8, 0.1),
  pllogis(
    q = seq(0.0001, 8, 0.1),
    shape = 1.56,
    scale = 3.04,
    lower.tail = FALSE),
  type = "l",
  xlab = "year",
  ylab = "S",
  ylim = c(0,1))
lines(
  seq(0.00001, 8, 0.1),
  pweibull(
    q = seq(0.0001, 8, 0.1),
    shape = 1.66,
    scale = 8.93,
    lower.tail = FALSE),
  type = "l",
  xlab = "year",
  ylab = "S",
  col = "blue")
lines(
  seq(0.0001, 8, 0.1),
  pgamma(
    q = seq(0.0001, 8, 0.1),
    shape = 1.74,
    rate = 1.27e-01 ,
    lower.tail = FALSE),
  type = "l",
  xlab = "year",
  ylab = "S",
  col = "green")
```

